{% set name = "fluids" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccca0829be53a53ad324974a52c6069a9129e71198b5d2aad1f704835fb3322a

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.5.0
    - python >=3.5
    - scipy >=0.9.0
    - sympy
    - pint
    - fuzzywuzzy

test:
  imports:
    - fluids

about:
  home: https://github.com/CalebBell/fluids
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Fluid dynamics component of Chemical Engineering Design Library (ChEDL)
  description: |
    Fluids is open-source software for engineers and technicians working in
    the fields of chemical, mechanical, or civil engineering. It includes
    modules for piping, fittings, pumps, tanks, compressible flow, open-channel
    flow, and more.

    The fluids library depends on the SciPy library to provide numerical 
    constants, interpolation, integration, and numerical solving functionality. 
    fluids runs on all operating systems which support Python, is quick to 
    install, and is free of charge. fluids is designed to be easy to use while 
    still providing powerful functionality. If you need to perform some fluid 
    dynamics calculations, give fluids a try.
  doc_url: https://fluids.readthedocs.io/
  dev_url: https://github.com/CalebBell/fluids

extra:
  recipe-maintainers:
    - volpatto
    - CalebBell
