travis:
  secure:
    BINSTAR_TOKEN: rz+G0aTGwr6MKgoKuC2plxrjtyUQ2jfGMsdltyP4fYdhgFIg2G3dlo5N6KVJDAQmE8oB5piGUaLJOLAwrx24W3whdrPk5Ic1vwTOu9p7TT3lXyPwmUl+GCYif6gvs0dO23Dcil4YOikhh+Odtsid5VAmjQwoPHglDK4uxdvVcfNID3kL+athoCPpukpQEIGmDfA5+/VA07xvPkeuzPQ00vK5dDT0ZgWdkEwJoR3aF67TjpfOrDuE2NurdGWpRNbGVqPQVdpTjii9+BEdJBByQN7pWo3l0Eq2k6VlVKEnhw6G4xNWJCEhR33Klvs/BK460WTTVkAVfQS8UEKdNh34K1PgFr9QjMXXzddT3UHOhp28dA+zibBmDfFYha4ksDyLYJnIpoNae7q/uL1gy6ds45sG3tbp6yx94dNWHamwK+4XxqhESM40rZgDBKNTKn9rNqVN+lvLXDYf48zXl8boBwzwHbd9oZybHHqxNeiSpGXZQ26foUXAw+jMTW0XVVG2iuhoomJwoWeDfooXt8/kU9kB30Ff+wehlYbeP4RYBWhU4ZoZs8HFDnAVdI0fVrIXIA0OZoSi2Qr4HMaEhzFMZXe00zu9K/r3gC7NeCDRU2r8Nk3Xo6Qbpbf63qn2sBKh4RetJlayHVBrH8GbNJ015PlnT97GzHfymRkSSfmAzOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
